---
apiVersion: v1
kind: Service
metadata:
  name: svc-b2c-pilot-node-aggr
  labels:
    solution-centre.name: snm-aml
    product-team.name: aml
    product.name: b2c-pilot-node
    application.tier: aggr
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    solution-centre.name: snm-aml
    product-team.name: aml
    product.name: b2c-pilot-node
    application.tier: aggr

