---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: depl-b2c-pilot-node-backend
  labels:
    solution-centre.name: snm-aml
    product-team.name: aml
    product.name: b2c-pilot-node
    application.tier: backend

spec:
  replicas: 1
  template:
    metadata:
      labels:
        solution-centre.name: snm-aml
        product-team.name: aml
        product.name: b2c-pilot-node
        application.tier: backend
    spec:
      containers:
      - name: b2c-pilot-node-backend
        image: 921141745046.dkr.ecr.us-west-2.amazonaws.com/snm-aml/aml_b2c-pilot-node_backend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: USER_VAR
          value: important information
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-b2c-pilot-node-mysql 
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-b2c-pilot-node-mysql
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap-b2c-pilot-node-mysql
              key: mysql.database
        - name: MYSQL_SERVER_ADDR
          valueFrom:
            configMapKeyRef:
              name: configmap-b2c-pilot-node-mysql
              key: mysql.server-addr
        - name: MYSQL_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-b2c-pilot-node-mysql
              key: mysql.server-port
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: configmap-b2c-pilot-node-redis
              key: redis.redis-url
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-b2c-pilot-node-redis
              key: redis.redis-port
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: secret-b2c-pilot-node-redis
              key: password



