---
apiVersion: v1
kind: Service
metadata:
  name: svc-b2c-pilot-node-back
  labels:
    solution-centre.name: snm-aml
    product-team.name: aml
    product.name: b2c-pilot-node
    application.tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    solution-centre.name: snm-aml
    product-team.name: aml
    product.name: b2c-pilot-node
    application.tier: backend

